name: Deploy develop to AWS EB
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Generate build UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1

      - name: Generate deployment package
        run: zip -r deploy.zip .

      - name: Deploy to AWS EB
        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: triptime-web
          environment_name: triptime-web-dev
          version_label: 'develop-${{ github.SHA }}-${{ steps.generate-uuid.outputs.uuid }}'
          version_description: 'branch: develop, commit: ${{ github.SHA }}'
          region: ap-southeast-2
          deployment_package: deploy.zip
          wait_for_environment_recovery: 60
